### ISSUE TITLE
delayed action

### ISSUE THREAD

**Issue by amir-arad** [camacho/yarn-or-npm#3]
Hi
I'm trying to migrate to yarn-or-npm, but I have this script in my `package.json`:
```
    "reset": "rimraf ./node_modules && npm install && npm test",
```
It's very helpfull for me when I need a clean-slate installation after changes to the dependencies.
if I replace `npm` with `yon` I'm getting a 'command not found' error because there is nothing installed by the time I get to the second command.
I need a way to resolve yarn-or-npm *before* running the first command, but execute it *afterwards*.
any ideas?

**Comment by camacho** [comment]
hi @amir-arad - i, unfortunately, do not have a good solution without pinning to either yarn or npm for the installation of `yarn-or-npm`. possible solutions:

```
"reset": "rimraf ./node_modules && npm install --save-dev yarn-or-npm && yon install && yon test",
```

```
"reset": "rimraf ./node_modules && yarn add -D yarn-or-npm && yon install && yon test",
```

**Comment by amir-arad** [comment]
thanks
