### ISSUE TITLE
Add feature to check project settings

### ISSUE THREAD

**Issue by rifler** [camacho/yarn-or-npm#4]
Using yarn or npm can be specific from project to project, rather than from computer to computer.

It would be great to check project like so:
If project top directory has yarn.lock - project uses yarn and user have to install yarn on his computer;
If it has package-lock.json - project uses npm;
If there is no lock file - npm ?

**Comment by camacho** [comment]
This seems reasonable. 

My proposal would be to:
1. From the `cwd` traverse to the package root using [`pkg-up`](https://github.com/sindresorhus/pkg-up)
1. Search for `yarn.lock` and `package.lock.json` and choose `yarn` or `npm` appropriately
1. If neither lockfile is found, default to using `yarn` and fallback to `npm`

**Comment by rifler** [comment]
> From the cwd, find the package root using pkg-up

Exactly, this is what I want to offer

> package.lock.json

package-lock.json

> If neither lockfile is found, use the current logic for deciding between yarn and npm

Not sure about this point, but ok, I suppose 95% of projects use lock files

Thanks for the reply!

**Comment by camacho** [comment]
@rifler thoughts on how to denote giving preference to one over the other?

**Comment by rifler** [comment]
maybe some setting in package.json ?

**Comment by camacho** [comment]
That's not a bad idea, but it will require some configuration choices and work. The change to support a project's client based on the lockfile shipped 👍
